import type { ProjectQuestion } from '../types/project';

// Common questions for all project types
const commonQuestions: ProjectQuestion[] = [
  {
    id: 'name',
    label: 'Project Name',
    type: 'text',
    required: true,
    placeholder: 'Enter your project name',
    transform: 'uppercase',
  },
  {
    id: 'logo',
    label: 'Project Logo',
    type: 'image',
    required: true,
    placeholder: 'Upload your project logo (PNG, JPG, SVG)',
  },
  {
    id: 'about',
    label: 'About',
    type: 'textarea',
    required: true,
    placeholder: 'Describe your project in detail',
  },
  {
    id: 'website',
    label: 'Website',
    type: 'url',
    required: false,
    placeholder: 'https://your-project.com',
  },
  {
    id: 'social',
    label: 'Social Link',
    type: 'url',
    required: false,
    placeholder: 'Enter your Telegram, Discord, or X link',
  },
];

export const PROJECT_QUESTIONS: Record<string, ProjectQuestion[]> = {
  blockchain: [
    ...commonQuestions,
    {
      id: 'layerType',
      label: 'Layer Type',
      type: 'select',
      required: true,
      options: ['Layer 1', 'Layer 2', 'Sidechain', 'Application Chain', 'Other'],
    },
    {
      id: 'otherLayerType',
      label: 'Other Layer Type',
      type: 'text',
      required: false,
      placeholder: 'Specify your layer type',
    },
    {
      id: 'consensus',
      label: 'Consensus Mechanism',
      type: 'select',
      required: true,
      options: ['Proof of Stake', 'Proof of Work', 'Proof of Authority', 'Other'],
    },
    {
      id: 'tps',
      label: 'Transactions Per Second (TPS)',
      type: 'number',
      required: true,
      placeholder: 'Enter TPS',
    },
    {
      id: 'blockTime',
      label: 'Block Time (seconds)',
      type: 'number',
      required: true,
      placeholder: 'Enter block time in seconds',
    },
    {
      id: 'nativeToken',
      label: 'Native Token',
      type: 'text',
      required: true,
      placeholder: 'Enter native token symbol',
    },
    {
      id: 'themeColor',
      label: 'Theme Color',
      type: 'color',
      required: true,
    },
    {
      id: 'regions',
      label: 'Select Regions',
      type: 'regions',
      required: true,
      icon: 'map',
      placeholder: 'Click to select regions on map',
    },
  ],
  defi: [
    ...commonQuestions,
    {
      id: 'type',
      label: 'DeFi Type',
      type: 'select',
      required: true,
      options: ['DEX', 'Lending', 'Yield Farming', 'Insurance', 'Other'],
    },
    {
      id: 'tvl',
      label: 'Total Value Locked (TVL)',
      type: 'number',
      required: false,
      placeholder: 'Enter TVL in USD',
    },
  ],
  nft: [
    ...commonQuestions,
    {
      id: 'type',
      label: 'NFT Type',
      type: 'select',
      required: true,
      options: ['Art', 'Gaming', 'Music', 'Virtual Real Estate', 'Other'],
    },
  ],
  bridge: [
    ...commonQuestions,
    {
      id: 'category',
      label: 'Bridge Category',
      type: 'select',
      required: true,
      options: ['Token', 'NFT', 'Message', 'Other'],
    },
    {
      id: 'otherCategory',
      label: 'Specify Category',
      type: 'text',
      required: false,
      placeholder: 'Describe your bridge category...',
    },
    {
      id: 'networks',
      label: 'Connected Networks',
      type: 'select',
      required: true,
      options: ['Base'],
    },
    {
      id: 'about',
      label: 'About',
      type: 'textarea',
      required: true,
      minLength: 50,
      maxLength: 200,
      placeholder: 'Describe your bridge in 50-200 characters...',
      className: 'whitespace-pre-wrap break-words',
    },
  ],
  infra: [
    ...commonQuestions,
    {
      id: 'type',
      label: 'Infrastructure Type',
      type: 'select',
      required: true,
      options: ['RPC', 'Indexer', 'Explorer', 'Validator', 'Other'],
    },
    {
      id: 'otherType',
      label: 'Specify Type',
      type: 'text',
      required: false,
      placeholder: 'Describe your infrastructure type...',
    },
  ],
  social: [
    ...commonQuestions,
    {
      id: 'category',
      label: 'Social Platform Category',
      type: 'select',
      required: true,
      options: ['Social Network', 'Content Platform', 'Community', 'Other'],
    },
    {
      id: 'otherCategory',
      label: 'Specify Category',
      type: 'text',
      required: false,
      placeholder: 'Describe your social platform category...',
    },
    {
      id: 'features',
      label: 'Key Features',
      type: 'textarea',
      required: true,
      minLength: 50,
      maxLength: 200,
      placeholder: 'List key features of your social platform...',
      className: 'whitespace-pre-wrap break-words',
    },
  ],
  ai: [
    ...commonQuestions,
    {
      id: 'category',
      label: 'AI Category',
      type: 'select',
      required: true,
      options: ['Language Model', 'Image Generation', 'Prediction', 'Other'],
    },
    {
      id: 'otherCategory',
      label: 'Specify Category',
      type: 'text',
      required: false,
      placeholder: 'Describe your AI category...',
    },
    {
      id: 'model',
      label: 'AI Model Type',
      type: 'select',
      required: true,
      options: ['LLM', 'GAN', 'Transformer', 'Other'],
    },
    {
      id: 'features',
      label: 'Key Features',
      type: 'textarea',
      required: true,
      minLength: 50,
      maxLength: 200,
      placeholder: 'List key features of your AI project...',
      className: 'whitespace-pre-wrap break-words',
    },
  ],
  oracle: [
    ...commonQuestions,
    {
      id: 'type',
      label: 'Oracle Type',
      type: 'select',
      required: true,
      options: ['Price Feed', 'Random Number', 'Weather', 'Sports', 'Other'],
    },
    {
      id: 'otherType',
      label: 'Specify Type',
      type: 'text',
      required: false,
      placeholder: 'Describe your oracle type...',
    },
    {
      id: 'updateFrequency',
      label: 'Update Frequency',
      type: 'select',
      required: true,
      options: ['Real-time', 'Every minute', 'Every hour', 'Daily', 'Other'],
    },
    {
      id: 'supportedNetworks',
      label: 'Supported Networks',
      type: 'text',
      required: true,
      placeholder: 'Base Polygon Solana',
      className: 'whitespace-pre-wrap break-words',
    },
  ],
  gamefi: [
    ...commonQuestions,
    {
      id: 'type',
      label: 'Game Type',
      type: 'select',
      required: true,
      options: ['MMORPG', 'Strategy', 'RPG', 'Action', 'Other'],
    },
    {
      id: 'otherType',
      label: 'Specify Type',
      type: 'text',
      required: false,
      placeholder: 'Describe your game type...',
    },
    {
      id: 'tokenomics',
      label: 'Tokenomics',
      type: 'textarea',
      required: true,
      placeholder: 'Describe your game tokenomics and economy...',
      className: 'whitespace-pre-wrap break-words',
    },
    {
      id: 'gameplay',
      label: 'Gameplay',
      type: 'textarea',
      required: true,
      placeholder: 'Describe your core gameplay mechanics...',
      className: 'whitespace-pre-wrap break-words',
    },
    {
      id: 'platform',
      label: 'Platform',
      type: 'select',
      required: true,
      options: ['Web', 'Mobile', 'PC', 'Console', 'Multi-platform'],
    },
  ],
  dao: [
    ...commonQuestions,
    {
      id: 'type',
      label: 'DAO Type',
      type: 'select',
      required: true,
      options: ['Protocol', 'Investment', 'Social', 'Grants', 'Other'],
    },
    {
      id: 'otherType',
      label: 'Specify Type',
      type: 'text',
      required: false,
      placeholder: 'Describe your DAO type...',
    },
    {
      id: 'governance',
      label: 'Governance Model',
      type: 'textarea',
      required: true,
      placeholder: 'Describe your governance model and voting mechanisms...',
      className: 'whitespace-pre-wrap break-words',
    },
    {
      id: 'supportedNetworks',
      label: 'Supported Networks',
      type: 'text',
      required: true,
      placeholder: 'Base Polygon Solana',
      className: 'whitespace-pre-wrap break-words',
    },
  ],
  other: [
    ...commonQuestions,
    {
      id: 'category',
      label: 'Project Category',
      type: 'text',
      required: true,
      placeholder: 'Describe your project category...',
    },
  ],
};
